config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'posts#index'

  resources :users, only: [:show]
  post 'subscribe/:follower_id/:following_id' => 'users#subscribe', as: 'subscribe'
  delete 'unsubscribe/:follower_id/:following_id' => 'users#unsubscribe', as: 'unsubscribe'

  resources :posts do
    resources :comments
  end

  resources :likes, only: [:create, :destroy]

  delete 'posts/image/:id/purge_image' => 'posts#purge_image', as: 'purge_image'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images, dependent: :destroy

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 50 }
  validates :text, presence: true, length: { maximum: 250 }

end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = 'users'

  has_one_attached :avatar

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_and_belongs_to_many :followings,
    class_name: 'User',
    foreign_key: :follower_id,
    association_foreign_key: :following_id,
    join_table: :followings_followers_tables

  has_and_belongs_to_many :followers,
    class_name: 'User',
    foreign_key: :following_id,
    association_foreign_key: :follower_id,
    join_table: :followings_followers_tables

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    @comment.user_id = current_user.id

    @comment.save

    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to @post
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post

  def create
    @like = @post.likes.build(user_id: current_user.id)

    @like.save

    redirect_to @post
  end

  def destroy
    @like = Like.find_by(post_id: @post.id, user_id: current_user.id)
    @like.destroy

    redirect_to @post
  end

  private
    def find_post
      @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to user_path(@post.user.id)
    else
      render 'new'
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    redirect_to user_path(@post.user.id)
  end

  def show
    @post = Post.find(params[:id])
  end

  def purge_image
    image = ActiveStorage::Attachment.find(params[:id])
    image.purge

    redirect_back(fallback_location: request.referer)
  end

  private
    def post_params
      params.require(:post).permit(:title, :text, :user_id, images: [])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_follower_and_following, only: [:subscribe, :unsubscribe]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.order(created_at: :desc)
  end

  def subscribe
    unless @following_user.followers.include?(@follower_user)
      @following_user.followers << @follower_user
    end

    redirect_back(fallback_location: request.referer)
  end

  def unsubscribe
    if @following_user.followers.include?(@follower_user)
      @following_user.followers.destroy(@follower_user)
    end

    redirect_back(fallback_location: request.referer)
  end

  private
    def find_follower_and_following
      @follower_user = User.find(params[:follower_id])
      @following_user = User.find(params[:following_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
  <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      &#x2630;
    </button>

    <%= link_to 'Lenta', root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="navbar-nav ml-auto">
        <div class="navbar-nav ml-auto">
          <% if user_signed_in? %>

            <div class="nav-item">
              <%= link_to 'My profile', user_path(current_user), class: 'btn btn-info mr-5' %>
            </div>

            <div class="nav-item">
              <span class="navbar-text">
                Hello, &nbsp;
              <span>
            </div>

            <div class="dropdown show">
              <%= link_to current_user.nickname, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </div>
            <div>
          <% else %>
            <div class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </div>
            <div class="nav-item">
              <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/comments/_comment.html.erb
<li>
  <p>
    <strong><%= comment.user.nickname %></strong> said:
  </p>
  <p>
    <%= comment.body %>
  </p>

  <% if current_user == comment.user %>
    <%= link_to 'Delete comment', post_comment_path(post_id: @post.id, id: comment.id),
      {
        class: 'btn btn-danger',
        method: :delete,
        data: { confirm: 'Are you sure' }
      }
    %>
  <% end %>
</li>

app/views/comments/_form.html.erb
<%= form_with url: [@post, @post.comments.build], scope: :comment, local: true do |f| %>

  <div>
    Text: <%= f.text_area :body %>
  </div>

  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'application/navbar' %>

    <div class="container">

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h2>Latest Posts: </h2>

<% @posts.each do |post| %>

  <div class="mb-4 border border-primary rounded p-3">
    <p><b>User's profile: </b><%= link_to "#{post.user.nickname}", user_path(post.user) %></p>

    <h3><%= post.title %></h3>

    <div class="post">

      <% if post.images.attached? %>

        <% if post.images.count > 1 %>

          <div class="d-flex justify-content-center">
            <div id="carouselExampleIndicators<%= post.id %>" data-interval="false" class="carousel slide bg-dark" data-ride="carousel">
              <ol class="carousel-indicators">
                <% post.images.each do |image| %>
                  <% if post.images.index(image) == 0 %>
                    <li data-target="#carouselExampleIndicators<%= post.id %>" data-slide-to="0" class="active"></li>
                  <% else %>
                    <li data-target="#carouselExampleIndicators<%= post.id %>" data-slide-to="<%= post.images.index(image) %>"></li>
                  <% end %>
                <% end %>
              </ol>

              <div class="carousel-inner">
                <% post.images.each do |image| %>

                  <% if post.images.index(image) == 0 %>

                    <div class="carousel-item active">
                      <%= image_tag image, class: 'd-block post-show' %>

                      <div class="text-center">
                        <% if current_user == post.user %>
                          <%= link_to 'Delete', purge_image_path(image),
                            {
                              method: :delete,
                              class: 'btn btn-danger',
                              data: { confirm: 'Are you sure?' }
                            }
                          %>
                        <% end %>
                      </div>
                    </div>

                  <% else %>

                    <div class="carousel-item">
                      <%= image_tag image, class: 'd-block post-show' %>

                      <div class="text-center">
                        <% if current_user == post.user %>
                          <%= link_to 'Delete', purge_image_path(image),
                            {
                              method: :delete,
                              class: 'btn btn-danger',
                              data: { confirm: 'Are you sure?' }
                            }
                          %>
                        <% end %>

                      </div>
                    </div>

                  <% end %>
                <% end %>
              </div>

              <a class="carousel-control-prev bg-secondary" href="#carouselExampleIndicators<%= post.id %>" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next bg-secondary" href="#carouselExampleIndicators<%= post.id %>" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>

          </div>

        <% else %>
          <div class="d-flex flex-column align-items-center">
            <% post.images.each do |image| %>

              <div>
                <%= image_tag image, size: 100, class: 'post-show' %>
              </div>

              <div class="text-center d-flex align-items-center">
                <% if current_user == post.user %>
                  <%= link_to 'Delete', purge_image_path(image),
                    {
                      method: :delete,
                      class: 'btn btn-danger',
                      data: { confirm: 'Are you sure?' }
                    }
                  %>
                <% end %>
              </div>

            <% end %>
          </div>
        <% end %>

      <% end %>
    </div>

    <div class="mt-3">
      <p><b>Likes: </b><%= post.likes.count %></p>
    </div>

    <%= link_to 'View post', post_path(post), class: 'btn btn-info mb-2' %>

    <% if current_user == post.user %>
      <div>
        <%= link_to 'Delete Post', post_path(post),
          {
            method: :delete,
            data: { confirm: 'Are you sure' },
            class: 'btn btn-danger mb-1'
          }
        %>
      </div>
    <% end %>
  </div>

<% end %>

app/views/posts/new.html.erb
<h2>New post</h2>

<%= form_with model: @post, local: true do |f| %>

  <% if @post && @post.errors.any? %>
    <div class="errors">
      Total errors: <%= @post.errors.count %>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %> <br/>
    <%= f.text_field :title, class: 'form-control w-25' %>
  </div>

  <div class="form-group">
    <%= f.label :text %> <br/>
    <%= f.text_area :text, class: 'form-control w-25' %>
  </div>

  <div>
    <%= f.label :images %><br />
    <%= f.file_field :images, multiple: true %>
  </div>

  <div class="">
    <%= f.submit class: 'btn' %>
  </div>

<% end %>

app/views/posts/show.html.erb
<div class="post">
  <p><b>User's profile: </b><%= link_to "#{@post.user.nickname}", user_path(@post.user) %></p>
  <h2 class="mt-5"><%= @post.title %></h2>
  <p><%= @post.text %></p>

  <% if @post.images.count > 1 %>

    <div class="d-flex justify-content-center">
      <div id="carouselExampleIndicators<%= @post.id %>" data-interval="false" class="carousel slide bg-dark" data-ride="carousel">
        <ol class="carousel-indicators">
          <% @post.images.each do |image| %>
            <% if @post.images.index(image) == 0 %>
              <li data-target="#carouselExampleIndicators<%= @post.id %>" data-slide-to="0" class="active"></li>
            <% else %>
              <li data-target="#carouselExampleIndicators<%= @post.id %>" data-slide-to="<%= @post.images.index(image) %>"></li>
            <% end %>
          <% end %>
        </ol>

        <div class="carousel-inner">
          <% @post.images.each do |image| %>

            <% if @post.images.index(image) == 0 %>

              <div class="carousel-item active">
                <%= image_tag image, class: 'd-block post-show' %>

                <div class="text-center">
                  <% if current_user == @post.user %>
                    <%= link_to 'Delete', purge_image_path(image),
                      {
                        method: :delete,
                        class: 'btn btn-danger',
                        data: { confirm: 'Are you sure?' }
                      }
                    %>
                  <% end %>
                </div>
              </div>

            <% else %>

              <div class="carousel-item">
                <%= image_tag image, class: 'd-block post-show' %>

                <div class="text-center">
                  <% if current_user == @post.user %>
                    <%= link_to 'Delete', purge_image_path(image),
                      {
                        method: :delete,
                        class: 'btn btn-danger',
                        data: { confirm: 'Are you sure?' }
                      }
                    %>
                  <% end %>

                </div>
              </div>

            <% end %>
          <% end %>
        </div>

        <a class="carousel-control-prev" href="#carouselExampleIndicators<%= @post.id %>" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon bg-secondary p-5" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators<%= @post.id %>" role="button" data-slide="next">
          <span class="carousel-control-next-icon bg-secondary p-5" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

    </div>

  <% else %>
    <div class="d-flex flex-column align-items-center">

      <% if @post.images.attached? %>
        <div>
          <%= image_tag @post.images.first, size: 100, class: 'post-show' %>
        </div>

        <div class="text-center d-flex align-items-center">
          <% if current_user == @post.user %>
            <%= link_to 'Delete', purge_image_path(@post.images.first),
              {
                method: :delete,
                class: 'btn btn-danger',
                data: { confirm: 'Are you sure?' }
              }
            %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if current_user == @post.user %>
    <div>
      <%= link_to 'Delete Post', post_path(@post),
        {
          method: :delete,
          data: { confirm: 'Are you sure' },
          class: 'btn btn-warning mb-1'
        }
      %>
    </div>
  <% end %>

</div>

<div>
  <% if user_signed_in? %>
    <% unless Like.where(post_id: @post.id, user_id: current_user.id).count > 0 %>
      <%= link_to 'Like', likes_path(post_id: @post.id),
        {
          method: :post,
          class: 'btn btn-success'
        }
      %>
    <% else %>
      <%= link_to 'Unlike', like_path(post_id: @post.id),
        {
          method: :delete,
          class: 'btn btn-danger'
        }
      %>
    <% end %>
  <% end %>

  <p><b>Likes: </b><%= @post.likes.count %></p>
</div>

<h2>
  <%= link_to 'Comments', "#comment-section#{@post.id}",
    {
      id: 'comment-link',
      data: { toggle: 'collapse' },
      role: 'button',
      aria: {
        expanded: 'false',
        controls: 'comment-section'
      }
    }
  %>
</h2>
<div id="comment-section<%= @post.id %>" class="collapse mb-5">
  <ol>
    <%= render @post.comments %>
  </ol>

  <% if user_signed_in? %>
    <h3>Add a comment:</h3>
    <%= render 'comments/form' %>
  <% end %>
</div>

app/views/users/show.html.erb
<% if current_user == @user %>
  <div>
    <%= link_to "New post", new_post_path, class: 'btn btn-primary' %>
  </div>
<% end %>

<div class="user">
  <h2 class="user-name"> <%= @user.nickname %></h2>

  <div>
    <p><b>followers:</b> <%= @user.followers.count %></p>
    <p><b>followings:</b> <%= @user.followings.count %></p>
  </div>

  <% if user_signed_in? && current_user != @user %>
    <div>
      <% unless @user.followers.include?(current_user) %>
        <%= link_to 'Follow', subscribe_path(follower_id: current_user.id, following_id: @user.id),
          {
            method: :post,
            class: 'btn btn-info mb-3'
          }
        %>
      <% else %>
        <%= link_to 'Unfollow', unsubscribe_path(follower_id: current_user.id, following_id: @user.id),
          {
            method: :delete,
            class: 'btn btn-danger mb-3'
          }
        %>
      <% end %>
    </div>
  <% end %>

  <% if @user.avatar.attached? %>
    <%= image_tag @user.avatar, size: 100, class: 'avatar-image rounded-circle' %>
  <% end %>

  <div class="row">
    <% @posts.each do |post| %>
      <div class="post border rounded border-primary m-1 col-3">

        <h2 class="mt-5"><%= post.title %></h2>

        <%= link_to "View This Post", post_path(post), class: 'btn btn-info' %>

        <% if post.images.attached? %>

          <% if post.images.count > 1 %>

            <div class="">
              <div id="carouselExampleIndicators<%= post.id %>" data-interval="false" class="carousel slide carousel-edit bg-dark" data-ride="carousel">
                <ol class="carousel-indicators">
                  <% post.images.each do |image| %>
                    <% if post.images.index(image) == 0 %>
                      <li data-target="#carouselExampleIndicators<%= post.id %>" data-slide-to="0" class="active"></li>
                    <% else %>
                      <li data-target="#carouselExampleIndicators<%= post.id %>" data-slide-to="<%= post.images.index(image) %>"></li>
                    <% end %>
                  <% end %>
                </ol>

                <div class="carousel-inner">
                  <% post.images.each do |image| %>

                    <% if post.images.index(image) == 0 %>

                      <div class="carousel-item active">
                        <%= image_tag image, class: 'd-block carousel-image' %>

                        <div class="text-center">
                          <% if current_user == @user %>
                            <%= link_to 'Delete', purge_image_path(image),
                              {
                                method: :delete,
                                class: 'btn btn-danger',
                                data: { confirm: 'Are you sure?' }
                              }
                            %>
                          <% end %>
                        </div>
                      </div>

                    <% else %>

                      <div class="carousel-item">
                        <%= image_tag image, class: 'd-block carousel-image' %>

                        <div class="text-center">
                          <% if current_user == @user %>
                            <%= link_to 'Delete', purge_image_path(image),
                              {
                                method: :delete,
                                class: 'btn btn-danger',
                                data: { confirm: 'Are you sure?' }
                              }
                            %>
                          <% end %>

                        </div>
                      </div>

                    <% end %>
                  <% end %>
                </div>

                <a class="carousel-control-prev bg-secondary" href="#carouselExampleIndicators<%= post.id %>" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next bg-secondary" href="#carouselExampleIndicators<%= post.id %>" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>

            </div>

          <% else %>
            <div class="d-flex flex-column align-items-center">
              <% post.images.each do |image| %>

                <div>
                  <%= image_tag image, size: 100, class: 'carousel-image' %>
                </div>

                <div class="text-center d-flex align-items-center">
                  <% if current_user == @user %>
                    <%= link_to 'Delete', purge_image_path(image),
                      {
                        method: :delete,
                        class: 'btn btn-danger',
                        data: { confirm: 'Are you sure?' }
                      }
                    %>
                  <% end %>
                </div>

              <% end %>
            </div>
          <% end %>

        <% end %>

        <div class="mt-3">
          <p><b>Likes: </b><%= post.likes.count %></p>
        </div>

        <% if current_user == @user %>
          <div>
            <%= link_to 'Delete Post', post_path(post),
              {
                method: :delete,
                data: { confirm: 'Are you sure' },
                class: 'btn btn-danger mb-1'
              }
            %>
          </div>
        <% end %>

      </div>
    <% end %>
  </div>

</div>